#! /bin/sh
set -e

### Gtk Theming Tweaks
if command -v gsettings > /dev/null then
        gtk30_config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
        if [ -f "$gtk30_config" ]; then
          cursor_theme="$(grep 'gtk-cursor-theme-name' "$gtk30_config" | sed 's/.*\s*=\s*//')"
          font_name="$(grep 'gtk-font-name' "$gtk30_config" | sed 's/.*\s*=\s*//')"
          gtk_theme="$(grep 'gtk-theme-name' "$gtk30_config" | sed 's/.*\s*=\s*//')"
          icon_theme="$(grep 'gtk-icon-theme-name' "$gtk30_config" | sed 's/.*\s*=\s*//')"
  
          gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
          gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
          gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme"
          gsettings set org.gnome.desktop.interface font-name "$font_name"
        fi
        ### Window Buttons Fix
        gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
fi



bindir=$(dirname "$0")
if [ "${bindir}" != "" ]; then bindir="${bindir}/"; fi

if [ ! -d "${XDG_RUNTIME_DIR}" ]
then
  echo "Error: XDG_RUNTIME_DIR '${XDG_RUNTIME_DIR}' does not exists"
  exit 1
fi

if [ -n "${WAYLAND_DISPLAY}" ] && [ -O "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]
then
  echo "Info: wayland endpoint '${WAYLAND_DISPLAY}' already exists, using it as host"
  export MIR_SERVER_WAYLAND_HOST="${WAYLAND_DISPLAY}"
  unset WAYLAND_DISPLAY
fi

if [ "${XDG_CONFIG_DIRS#*/etc/xdg/xdg-miriway}" = "${XDG_CONFIG_DIRS}" ]
then
  export XDG_CONFIG_DIRS="/etc/xdg/xdg-miriway:${XDG_CONFIG_DIRS:-/etc/xdg}"
fi

if command -v Xwayland > /dev/null
then
  export MIR_SERVER_ENABLE_X11=1
fi

exec "${bindir}"miriway-shell "$@"
