#! /bin/bash
set -e
if [ "$SNAP_NAME" == "miriway" ]; then
  unset __EGL_VENDOR_LIBRARY_DIRS
  unset GBM_BACKENDS_PATH
  unset LIBINPUT_QUIRKS_DIR
  unset DRIRC_CONFIGDIR
  unset XDG_DESKTOP_PORTAL_DIR
  unset AMDGPU_ASIC_ID_TABLE_PATHS

  PATH="$(echo "$PATH" | sed "s#$SNAP[^:]*:##g")"
fi
exec "$@"
