#! /bin/sh
set -e

bindir=$(dirname "$0")
if [ "${bindir}" != "" ]; then bindir="${bindir}/"; fi

if [ ! -d "${XDG_RUNTIME_DIR}" ]
then
  echo "Error: XDG_RUNTIME_DIR '${XDG_RUNTIME_DIR}' does not exists"
  exit 1
fi

if [ -n "${WAYLAND_DISPLAY}" ] && [ -O "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]
then
  echo "Info: wayland endpoint '${WAYLAND_DISPLAY}' already exists, using it as host"
  export MIR_SERVER_WAYLAND_HOST=${WAYLAND_DISPLAY}
  unset WAYLAND_DISPLAY
fi

config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
if [ ! -e "$config_dir" ]
then
  mkdir -p "$config_dir"
fi

config_file=$config_dir/miriway-shell.config

if [ ! -e "${config_file}" ]
then
  echo "x11-window-title=Miriway" >> "${config_file}"
  echo "idle-timeout=600" >> "${config_file}"

  if command -v Xwayland > /dev/null
  then
    echo "enable-x11=" >> "${config_file}"
  fi

  if command -v gsettings > /dev/null
  then
    keymap_index=$(gsettings get org.gnome.desktop.input-sources current | cut -d\  -f 2)
    keymap=$(gsettings get org.gnome.desktop.input-sources sources | grep -Po "'[[:alpha:]]+'\)" | sed -ne "s/['|)]//g;$((keymap_index+1))p")
    echo "keymap=${keymap}" >> "${config_file}"
  fi

  if command -v swaybg > /dev/null; then
    # Try copying GNOME background
    if command -v gsettings > /dev/null; then
      background=$(gsettings get org.gnome.desktop.background picture-uri | sed -Ee "s|[^:]*://(.*\.png)'$|\1|")
      if [ ! -e "${background}" ]; then
        unset background
      fi
    fi

    echo "shell-component=swaybg -i \"${background:-/usr/share/backgrounds/warty-final-ubuntu.png}\"" >> "${config_file}"
  fi

  if command -v waybar > /dev/null; then
    echo "shell-component=waybar" >> "${config_file}"
  fi

  echo "shell-meta=a:wofi --show drun --location top_left" >> "${config_file}"
  echo "ctrl-alt=t:miriway-terminal" >> "${config_file}"
fi

exec "${bindir}"miriway-shell "$@"