#!/bin/sh -e

mkdir -p /usr/share/wayland-sessions/ /usr/lib/systemd/user/
sed -e s/miriway-session/miriway.session/ "$SNAP"/usr/share/wayland-sessions/miriway.desktop > /usr/share/wayland-sessions/miriway.desktop
cp "$SNAP"/usr/lib/systemd/user/miriway-session.target /usr/lib/systemd/user/

xdg_config=/etc/xdg/xdg-miriway

miriway_config="${xdg_config}/miriway-shell.config"
waybar_config="${xdg_config}/waybar/config"
waybar_style="${xdg_config}/waybar/style.css"

###################################################################
# Ensure we have a miriway-shell config file with the fixed options
mkdir -p -m 755 "$(dirname "${miriway_config}")"

cat <<EOT > "${miriway_config}"
x11-window-title=Miriway
idle-timeout=600
app-env-amend=XDG_SESSION_TYPE=wayland:GTK_USE_PORTAL=0:XDG_CURRENT_DESKTOP=Miriway:GTK_A11Y=none

ctrl-alt=t:miriway-unsnap /snap/${SNAP_INSTANCE_NAME}/current/usr/bin/miriway-terminal

shell-component=wbg -s /snap/${SNAP_INSTANCE_NAME}/current/usr/share/backgrounds/miriway.png
shell-component=waybar --config="${waybar_config}" --style="${waybar_style}"
shell-component=swaync
shell-component=/snap/${SNAP_INSTANCE_NAME}/usr/libexec/polkit-mate-authentication-agent-1
shell-component=miriway-unsnap /snap/${SNAP_INSTANCE_NAME}/current/usr/bin/synapse --startup
shell-meta=a:miriway-unsnap /snap/${SNAP_INSTANCE_NAME}/current/usr/bin/synapse

meta=Left:@dock-left
meta=Right:@dock-right
meta=Space:@toggle-maximized
meta=Home:@workspace-begin
meta=End:@workspace-end
meta=Page_Up:@workspace-up
meta=Page_Down:@workspace-down
ctrl-alt=BackSpace:@exit
EOT
# Ensure we have a miriway-shell config file with the fixed options
###################################################################

###################################################################
# Ensure we have a waybar config file with the fixed options
mkdir -p -m 755 "$(dirname "${waybar_config}")"
# Expand @CPU_ICONS@ to one {icon<n>} per thread on this machine
threads=$(grep -c '^cpu[0-9]' /proc/stat)
cpu_icons=$(printf '{icon%s}' $(seq 0 $((threads - 1))))
sed "s|@CPU_ICONS@|${cpu_icons}|" "$SNAP"/waybar/config > "${waybar_config}"
cp "$SNAP"/waybar/style.css "${waybar_style}"
###################################################################
