#!/bin/sh

rm /usr/share/wayland-sessions/miriway.desktop /etc/xdg/xdg-miriway/miriway-shell.config
rm /usr/lib/systemd/user/miriway-session.target /usr/libexec/miriway-session-startup  /usr/libexec/miriway-session-shutdown